from erori.exceptii import ValidError, RepoError

class Teste:
    def ruleaza_teste(self):
        pass